name: run test and pipeline
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: false
          activate-environment: quant
          environment-file: environment.yaml
          python-version: 3.9
      - uses: iterative/setup-cml@v1
      - name: Run pytest
        shell: bash -l {0}
        run: |
          pytest --junit-xml pytest.xml
      - name: Upload Unit Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Unit Test Results (Python ${{ matrix.python-version }})
          path: pytest.xml
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: pytest.xml
